INSERT INTO public.reports (id, allauthors, numauthfrc, title, reptype, eventstartdate, eventenddate, magazine, publisher, eventname, eventplace, pubplace, startpage, endpage, catwos, catscopus, catissn, catisbn, catothers, pubyear, author) VALUES ('6efda5e0-a6c7-4f16-bf97-b3181c951fce', 'Чернозуб С.П.
                
                ', 1, 'Коллегия, а не "клуб учёных". Идея Лейбница о создании Академии       наук в России и перипетии её истолкования
                
                ', true, '2016-12-01', '2016-12-03', 'ИФ РАН', 'ИФ РАН', 'Императорская академия наук и художеств, Академия наук СССР, Российская академия наук - триединая академия. К 290-летию основания РАН', 'Москва', 'Москва', 23, 34, false, false, false, true, false, 2016, '4a98209f-e2ac-4a02-b636-c4d87e5286a7');
INSERT INTO public.reports (id, allauthors, numauthfrc, title, reptype, eventstartdate, eventenddate, magazine, publisher, eventname, eventplace, pubplace, startpage, endpage, catwos, catscopus, catissn, catisbn, catothers, pubyear, author) VALUES ('ea525f49-bf94-44f4-ba65-d7ac2bf24460', 'Лейбин В.М.', 1, 'Образ ребёнка в процессе обучения с зеркалом                ', true, '2016-10-13', '2016-10-14', 'Сборник трудов', 'ФИЦ ИУ РАН', 'Всесоюзная научная конференция "Лицо человека в пространстве общения"', 'Москва', 'Москва', 0, 0, false, false, true, false, false, 2016, '610c7fd7-b8b3-4fe2-b7ac-1c8630524922');
INSERT INTO public.reports (id, allauthors, numauthfrc, title, reptype, eventstartdate, eventenddate, magazine, publisher, eventname, eventplace, pubplace, startpage, endpage, catwos, catscopus, catissn, catisbn, catothers, pubyear, author) VALUES ('bdcf204c-d9d1-4335-9845-dd8d3f60e9a6', 'Осипов С.Н., Дубовский С.В.', 2, 'Расчёт экономического роста США, Китая, России                ', true, '2017-06-12', '2017-05-16', 'Сборник трудов конференции', 'УРСС', 'САИТ 2017', 'Калиниград', 'Москва', 25, 29, false, false, true, true, false, 2017, '75fc54c2-7bf6-40b1-9570-77ea64779faa');
INSERT INTO public.reports (id, allauthors, numauthfrc, title, reptype, eventstartdate, eventenddate, magazine, publisher, eventname, eventplace, pubplace, startpage, endpage, catwos, catscopus, catissn, catisbn, catothers, pubyear, author) VALUES ('23d5ebab-3386-4e64-a3cc-1fadcbe23e3d', 'Sazonov Boris, Korolev Anton, Kozhevnikov Dmitry
                
                ', 3, '2747 Day II, Topic 3: Permanent Designing as a way to socio-technical systems sustainnability achieving         
                
                ', false, '2016-07-24', '2016-07-30', 'Part 1', 'ISSS-2016', '60th Annual Confenece and Meeting of the Internetional Society for the Systems Sciences "Realizing Sustainable Futures in Socio-Ecological Systems"', 'Boulder, Colorado', 'Boulder, Colorado', 24, 30, false, false, true, false, false, 2016, '6e18210d-474b-4885-9741-f337238e9d22');
INSERT INTO public.reports (id, allauthors, numauthfrc, title, reptype, eventstartdate, eventenddate, magazine, publisher, eventname, eventplace, pubplace, startpage, endpage, catwos, catscopus, catissn, catisbn, catothers, pubyear, author) VALUES ('23389ec6-33ea-413c-a24d-5d08b3fbdb43', 'Сазонов Б.В., Королев А.С., Кожевников Д.Е.
                
                ', 3, 'Социотехнические системы как объект перманентного проектирования и управления
                
                ', false, '2016-10-03', '2016-10-05', 'Материалы 9-й международной конференции MLSD''2016, том 2', 'ИПУ РАН', 'Конференция "Управление развитием крупномасштабных систем MLSD''2106', 'Москва, Россия', 'Москва', 345, 347, false, false, false, false, true, 2016, '6e18210d-474b-4885-9741-f337238e9d22');